export const REQUEST_STUDENT_DETAILS = 'student-details/REQUEST_STUDENT_DETAILS'
export const RECEIVE_STUDENT_DETAILS = 'student-details/RECEIVE_STUDENT_DETAILS'
export const REQUEST_FILTERED_NAMES = 'filter-names/REQUEST_FILTERED_NAMES'
export const RECEIVE_FILTERED_NAMES = 'filter-names/RECEIVE_FILTERED_NAMES'